### ISSUE TITLE
NPE	at org.reaktivity.command.log.internal.LoggableStream.handleData(LoggableStream.java:234)

### ISSUE THREAD

**Issue by akrambek** [reaktivity/command-log.java#30]
Running command log resulting in 

``` 
Exception in thread "main" java.lang.NullPointerException
	at org.reaktivity.command.log.internal.LoggableStream.handleData(LoggableStream.java:234)
	at org.reaktivity.command.log.internal.LoggableStream.handleFrame(LoggableStream.java:136)
	at org.reaktivity.command.log.internal.spy.OneToOneRingBufferSpy.spy(OneToOneRingBufferSpy.java:120)
	at org.reaktivity.command.log.internal.LoggableStream.process(LoggableStream.java:99)
	at org.reaktivity.command.log.internal.LogStreamsCommand.run(LogStreamsCommand.java:132)
	at org.reaktivity.command.log.internal.LogCommand.main(LogCommand.java:93)
```

**Comment by akrambek** [comment]
https://github.com/reaktivity/command-log.java/pull/31
